# permissions for end users to view petclinicansibles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: petclinicansible-viewer-role
rules:
- apiGroups:
  - demo.ansible.op.com
  resources:
  - petclinicansibles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - demo.ansible.op.com
  resources:
  - petclinicansibles/status
  verbs:
  - get
